util/networkutil.py
Fixes #NA
General fixes towards deployment of prod
=> Fix networkutil

.gitignore, .pylintrc, dftool, util/test/test_dftool.py
=> Fix #154 - dftool manyrandom fails, other issues

util/calcrewards.py, util/test/test_calcrewards.py, util/test/test_tousd.py, util/tousd.py
Towards #206.
Will also help https://github.com/oceanprotocol/df-web/issues/105
=> Refactor: move the to-usd calculations to a new module tousd.py

dftool, util/calcrewards.py, util/test/test_calcrewards.py, util/test/test_end-to-end.py
=> Fix #206 - Bound max APY locally, not just globally

dftool, util/csvs.py
=> Fix #213 - In DF3 dispense, poolinfo-137.csv had no entries

contracts/ve/DelegationProxy.vy, contracts/ve/VotingEscrowDelegation.vy, contracts/ve/veBoost.vy, util/test/veOcean/test_delegation.py
- Added delegation contracts and a little test
=> veOcean delegation system

contracts/ve/FeeDistributor.vy, contracts/ve/veOcean.vy, util/test/veOcean/test_fee_dist.py
- veOcean fee distribution contract and tests
=> veOcean fee distribution

.github/workflows/test.yml, contracts/ve/veAllocate.sol, util/test/veOcean/test_allocate_dt.py
Fixes # .
- add setBatchAllocation to veAllocate.sol, which emits a new event called AllocationSetMultiple
- 
(PS: Once approved and merged, I will copy the changes to ocean-contracts, release a new version and update subgraph)
=> add setBatchAllocation

README-dist-ops.md, dftool, util/approvedfilter.py, util/cleancase.py, util/csvs.py, util/test/test_approvedfilter.py, util/test/test_csvs.py
Fixes #281
- Rename poolvols csv to nftvols
=> Rename poolvols csv

contracts/ve/FeeEstimate.vy, util/test/veOcean/test_fee_dist.py
Fixes # .
- create new contract that estimates amount to be claimed
- 
-
=> add FeeEstimate contract

util/calcrewards.py
Towards #347. This PR refactors calcrewards itself, finally:)
=> Towards #347 - Refactor calcrewards, for simplicity.

util/calcrewards.py, util/query.py, util/test/test_end-to-end.py
=> Fix #354 test_end-to-end failing, likely from recent RF changes

util/oceanutil.py, util/test/test_query.py
=> Small refactor of oceanutil and test_query.py

dftool, util/calcrewards.py, util/cleancase.py, util/test/test_calcrewards.py, util/test/test_cleancase.py
=> Fix #357: Implement usable_active_budget = min(mult * DCV, budget)

util/test/test_query.py
=> Fix #414 - accounts

util/oceantestutil.py
=> Fix #427 - oceantestutil.py sets an int for bal_before

util/oceantestutil.py
=> Fix #440 - small refactor for veOCEAN

util/query.py, util/test/test_query.py
=> Fix #444 - queryAllocations() & queryVebalances() fail if no data at all

util/test/test_DFRewards.py, util/test/test_dftool.py, util/test/test_query.py
=> Fix #429 - make test_dftool more reliable & faster

dftool
=> Fix #452 & #454: dftool.do_calc input files & f-string

util/calcrewards.py, util/cleancase.py, util/test/test_calcrewards.py, util/test/test_cleancase.py
=> Fix #455: calcRewards() can't handle symbols of improper case

util/csvs.py, util/query.py, util/test/test_csvs.py
=> Fix #459 - csvs.py better support for nftinfo incl tests

dftool, util/calcrewards.py, util/cleancase.py, util/constants.py, util/csvs.py, util/query.py, util/test/test_calcrewards.py, util/test/test_cleancase.py, util/test/test_csvs.py, util/test/test_dftool.py, util/test/test_query.py, util/tok.py, util/tousd.py
Reverting from main.
Merging after DF22 ends.
[Fix creator => owner - Targeting DF23]
https://github.com/oceanprotocol/df-py/issues/469
=> Revert "Fix #403: Near-term RF tuning"

.github/workflows/black.yml, dftool, util/csvs.py, util/query.py, util/test/test_dftool.py, util/test/test_query.py
Fixes #443 
- Added dftool `calculate_passive` command
- Added new query function `queryPassiveRewards`
- Query and dftool command tests
- Fixed black flow to use the version from requirements.txt (in accordance with brownie)
=> Add dftool `calculate_passive` command

dftool, util/test/test_getrate.py
Fixes #475
- Order the args correctly
=> Fix dftool do_nftinfo bug

util/constants.py
Enable publisher rewards starting with DF25
=> Enable publisher rewards

dftool
Fixes #493
As outlined inside https://github.com/oceanprotocol/df-py/pull/313
=> Cleaning up df_main() for pylint.

dftool, util/test/test_dftool.py
Fixes #497 
- Inits dev wallets to have balanceOf(OCEAN.address) > 0
As outlined in https://github.com/oceanprotocol/df-py/issues/313
=> Helper command: initdevwallet

requirements.txt, util/test/test_query.py
Fixes #437
- This fixes most of the tests related to Aquarius by simply updating the dids
- There is one remaining test that didn't work when swapping the dids, I'll look more into that separately: https://github.com/oceanprotocol/df-py/issues/510
=> Fixing Aquarius tests

.github/workflows/mypy.yml, .gitignore, dftool, requirements.txt
=> Fix #544: Small refactors for remote CI

dftool
=> Fix #555: Some dftool methods break unix & dftool conventions

dftool
Towards #540
What I did here: simply update the dftool commands to lay out what they need to do.
In future PRs: flesh out implementation of Challenge DF, and of Predictoor DF. Update dftool behavior accordingly too.
=> Towards #540: Revise df-py arch for 3 DF substreams

pytest.ini, util/networkutil.py
=> Fix #549: Suppress/fix warnings in tests

.github/workflows/test.yml
=> Fix #438: Switch to new barge

.github/workflows/test.yml
=> Fix #566: CI fails: Workflow file has syntax error

util/test/test_DFRewards_allocate_gas.py
=> Fix #568 - test_insufficient_gas_reverts fails

util/test/veOcean/test_lock.py
=> Fix #569 - test_alice_locks_tokens fails

util/test/test_query.py, util/test/veOcean/test_lock.py
Towards #570. And with refactoring
=> Towards #570 - test_query.py::test_all fails

util/test/veOcean/test_lock.py, util/test/veOcean/test_whitelist_sc.py
=> For #575, skip tests until fixed

.pylintrc, dftool, util/base18.py, util/dispense.py, util/oceantestutil.py, util/oceanutil.py, util/query.py, util/test/test_DFRewards.py, util/test/test_DFRewards_withdraw.py, util/test/test_base18.py, util/test/test_dftool.py, util/test/test_dispense.py, util/test/test_query.py, util/test/test_vesting_schedule.py, util/test/veOcean/test_delegation.py, util/test/veOcean/test_estimateclaim.py, util/test/veOcean/test_fee_dist.py, util/test/veOcean/test_fee_estimate.py, util/test/veOcean/test_lock.py, util/test/veOcean/test_whitelist_sc.py, util/vesting_schedule.py
=> Fix #577: toBase18 -> to_wei, fromBase18 -> from_wei

util/test/veOcean/test_lock.py, util/test/veOcean/test_whitelist_sc.py
=> For #575: unskip tests

README.md, requirements.txt, util/judge.py, util/test/test_judge.py
=> Use subgraph instead of Polygon Scan in judge script.

.github/workflows/test.yml, util/query.py, util/test/test_query.py
=> Fix #570 - test_query.py::test_all fails

util/blocktime.py, util/test/test_blocktime_eth_mainnet.py, util/test/test_blocktime_ganache.py
=> Fix tests on non-UTC machines.

.github/workflows/flow.yml
=> Fix CI by removing 2nd mumbai line for brownie

util/challenge/judge.py
=> Use Kraken instead of Binance for df challenge.

README.md, dftool, util/networkutil.py, util/test/conftest.py, util/test/test_DFRewards.py, util/test/test_DFRewards_allocate_gas.py, util/test/test_DFRewards_withdraw.py, util/test/test_Simpletoken.py, util/test/test_blocktime_ganache.py, util/test/test_contract_persistence.py, util/test/test_dispense.py, util/test/test_networkutil.py, util/test/test_vesting_schedule.py, util/test/veOcean/test_allocate_dt.py, util/test/veOcean/test_delegation.py, util/test/veOcean/test_deploy.py, util/test/veOcean/test_estimateclaim.py, util/test/veOcean/test_fee_dist.py, util/test/veOcean/test_fee_estimate.py, util/test/veOcean/test_lock.py, util/test/veOcean/test_whitelist_sc.py
Will help in #491 and elsewhere
=> Towards #491: introduce connectDev()

util/test/veOcean/test_allocate_dt.py, util/test/veOcean/test_delegation.py, util/test/veOcean/test_deploy.py, util/test/veOcean/test_estimateclaim.py, util/test/veOcean/test_fee_dist.py, util/test/veOcean/test_fee_estimate.py, util/test/veOcean/test_lock.py, util/test/veOcean/test_whitelist_sc.py
=> Helps #599. Properly disconnect network after test is over

.github/workflows/dispense_passive.yml, .github/workflows/flow.yml
=> Add caching to dispense active and passive flows.

df_py/util/blocktime.py, df_py/util/dftool_arguments.py, df_py/util/dftool_module.py, df_py/util/test/test_blocktime_ganache.py, df_py/util/test/test_dftool_arguments.py, df_py/util/test/test_dftool_ganache.py
=> Add some coverage for dftool arguments.

df_py/challenge/calcrewards.py, df_py/challenge/csvs.py, df_py/challenge/test/test_challenge_calcrewards.py, df_py/challenge/test/test_challenge_csvs.py, df_py/util/constants.py, df_py/util/dftool_module.py, df_py/util/test/test_dftool_ganache.py, df_py/util/test/test_vesting_schedule.py, df_py/util/vesting_schedule.py
=> Add challenge rewards calculations

.github/workflows/test-dfsql.yml, df_py/challenge/judge.py, df_py/challenge/test/test_dftool_challenge.py, df_py/util/dftool_arguments.py, df_py/util/dftool_module.py, df_py/util/test/test_dftool_ganache.py, df_py/util/test/test_dftool_noganache.py
=> Add the testing args context separately.

df_py/util/blocktime.py, df_py/util/test/test_blocktime_ganache.py, df_py/util/test/test_getrate.py
=> Use blocktime instead of local time

df_py/util/dftool_module.py
=> Correct capitalisation in dftool_module variables.

df_py/util/dftool_module.py
=> Fix #697 -- 'dftool' without args causes error, should return help

.bumpversion.cfg, Dockerfile, README.md, setup.py
=> Remove bumpcfg and fix docker build

.github/workflows/pylint.yml, df_py/util/dftool_module.py, df_py/util/http_provider.py, df_py/util/oceantestutil.py, df_py/util/oceanutil.py, df_py/util/request.py
=> Fix #810 Codebase has many pylint errors

df_py/volume/test/test_calcrewards.py
Towards #812
- replace 29 occurrences of 4-line patch with 1-line patch
=> Towards #812 [SW eng, DX] 4-liner --> 1-liner (x 29)
